version: '3.9'
services:
  server:
    build:
      context: .
      target: development
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    container_name: server
    command: npm run dev
